"""machines and order item machine fk

Revision ID: 4112686ed4f1
Revises: 849f3aec1347
Create Date: 2026-09-22 02:00:43.491523
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4112686ed4f1'
down_revision: str | None = '849f3aec1347'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('technology', sa.String(length=20), nullable=False),
    sa.Column('build_volume_x_mm', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('build_volume_y_mm', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('build_volume_z_mm', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('power_watts', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('cost_per_hour', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True),
    sa.Column('speed_profile', sa.JSON(), nullable=True),
    sa.Column('compatible_materials', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_organization_id'), 'machines', ['organization_id'], unique=False)
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.create_foreign_key(
            'fk_order_items_machine_id', 'machines', ['machine_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items') as batch_op:
        batch_op.drop_constraint('fk_order_items_machine_id', type_='foreignkey')
    op.drop_index(op.f('ix_machines_organization_id'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###
