"""cost profiles and quotes

Revision ID: 5923faafc2c8
Revises: 907b76858a80
Create Date: 2026-09-21 21:46:30.946465
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5923faafc2c8'
down_revision: str | None = '907b76858a80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('energy_cost_per_kwh', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=False),
    sa.Column('labor_cost_per_hour', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('packaging_cost_flat', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('waste_percentage', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.Column('fees_percentage', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.Column('profit_margin_percentage', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=False),
    sa.Column('tax_percentage', sa.Numeric(precision=6, scale=3, asdecimal=False), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_profiles_organization_id'), 'cost_profiles', ['organization_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('project_version_id', sa.Uuid(), nullable=True),
    sa.Column('cost_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('cost_breakdown_snapshot', sa.JSON(), nullable=False),
    sa.Column('production_cost', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('suggested_price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cost_profile_id'], ['cost_profiles.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_cost_profile_id'), 'quotes', ['cost_profile_id'], unique=False)
    op.create_index(op.f('ix_quotes_organization_id'), 'quotes', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_organization_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_cost_profile_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_cost_profiles_organization_id'), table_name='cost_profiles')
    op.drop_table('cost_profiles')
    # ### end Alembic commands ###
