"""ai jobs and attempts

Revision ID: 5ab00aa57e43
Revises: 46fdf00aa9be
Create Date: 2026-09-21 17:56:49.087365
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5ab00aa57e43'
down_revision: str | None = '46fdf00aa9be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('input_spec', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('queue_name', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('result_file_id', sa.Uuid(), nullable=True),
    sa.Column('result_project_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['result_project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_ai_jobs_org_idempotency')
    )
    op.create_index(op.f('ix_ai_jobs_organization_id'), 'ai_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_project_id'), 'ai_jobs', ['project_id'], unique=False)
    op.create_table('ai_job_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_job_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ai_job_id'], ['ai_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_job_attempts_ai_job_id'), 'ai_job_attempts', ['ai_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_job_attempts_ai_job_id'), table_name='ai_job_attempts')
    op.drop_table('ai_job_attempts')
    op.drop_index(op.f('ix_ai_jobs_project_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_organization_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    # ### end Alembic commands ###
