"""materials inventory items and movements

Revision ID: 9a6d1ea40673
Revises: 5923faafc2c8
Create Date: 2026-09-21 22:26:26.006510
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9a6d1ea40673'
down_revision: str | None = '5923faafc2c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('density_g_cm3', sa.Numeric(precision=8, scale=4, asdecimal=False), nullable=True),
    sa.Column('cost_per_kg', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_organization_id'), 'materials', ['organization_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=3, asdecimal=False), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('minimum_stock', sa.Numeric(precision=14, scale=3, asdecimal=False), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_material_id'), 'inventory_items', ['material_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_organization_id'), 'inventory_items', ['organization_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inventory_item_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3, asdecimal=False), nullable=False),
    sa.Column('reference_order_id', sa.Uuid(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4, asdecimal=False), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_organization_id'), 'inventory_movements', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_movements_organization_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventory_items_organization_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_material_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_materials_organization_id'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
