"""billing plans subscriptions and events

Revision ID: a64f7589aaf0
Revises: 4112686ed4f1
Create Date: 2026-09-22 02:33:18.848663
"""
import uuid
from collections.abc import Sequence
from datetime import UTC, datetime

from alembic import op
import sqlalchemy as sa


revision: str = 'a64f7589aaf0'
down_revision: str | None = '4112686ed4f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Plano semente de desenvolvimento — NÃO é um plano comercial (ver
# ARCHITECTURE.md, nota "Status na Fase 18A"). Existe só para o ambiente
# ter algo para testar contra antes de qualquer decisão real de preço.
_DEV_PLAN_CODE = "dev_unlimited"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_period_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('billing_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_billing_events_provider_external_id')
    )
    op.create_index(op.f('ix_billing_events_organization_id'), 'billing_events', ['organization_id'], unique=False)
    op.create_table('plan_entitlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('limit_type', sa.String(length=20), nullable=False),
    sa.Column('bool_value', sa.Boolean(), nullable=True),
    sa.Column('numeric_value', sa.Numeric(precision=14, scale=2, asdecimal=False), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'key', name='uq_plan_entitlements_plan_key')
    )
    op.create_index(op.f('ix_plan_entitlements_plan_id'), 'plan_entitlements', ['plan_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_provider', sa.String(length=20), nullable=False),
    sa.Column('external_subscription_id', sa.String(), nullable=True),
    sa.Column('external_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    # ### end Alembic commands ###

    _seed_dev_plan()


def _seed_dev_plan() -> None:
    now = datetime.now(UTC)
    plan_id = uuid.uuid4()

    plans_table = sa.table(
        "plans",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("is_active", sa.Boolean()),
        sa.column("trial_period_days", sa.Integer()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        plans_table,
        [
            {
                "id": plan_id,
                "code": _DEV_PLAN_CODE,
                "name": "Desenvolvimento (interno, sem custo real)",
                "is_active": True,
                "trial_period_days": None,
                "created_at": now,
                "updated_at": now,
            }
        ],
    )

    entitlements_table = sa.table(
        "plan_entitlements",
        sa.column("id", sa.Uuid()),
        sa.column("plan_id", sa.Uuid()),
        sa.column("key", sa.String()),
        sa.column("limit_type", sa.String()),
        sa.column("bool_value", sa.Boolean()),
        sa.column("numeric_value", sa.Numeric()),
    )
    op.bulk_insert(
        entitlements_table,
        [
            {
                "id": uuid.uuid4(),
                "plan_id": plan_id,
                "key": "max_projects",
                "limit_type": "numeric",
                "bool_value": None,
                "numeric_value": 20,
            },
            {
                "id": uuid.uuid4(),
                "plan_id": plan_id,
                "key": "max_ai_jobs_per_period",
                "limit_type": "numeric",
                "bool_value": None,
                "numeric_value": 50,
            },
            {
                "id": uuid.uuid4(),
                "plan_id": plan_id,
                "key": "max_storage_mb",
                "limit_type": "numeric",
                "bool_value": None,
                "numeric_value": 500,
            },
            {
                "id": uuid.uuid4(),
                "plan_id": plan_id,
                "key": "feature.ai_text_to_3d",
                "limit_type": "boolean",
                "bool_value": True,
                "numeric_value": None,
            },
            {
                "id": uuid.uuid4(),
                "plan_id": plan_id,
                "key": "feature.ai_image_to_3d",
                "limit_type": "boolean",
                "bool_value": True,
                "numeric_value": None,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plan_entitlements_plan_id'), table_name='plan_entitlements')
    op.drop_table('plan_entitlements')
    op.drop_index(op.f('ix_billing_events_organization_id'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_table('plans')
    # ### end Alembic commands ###
